//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PalcoNet.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Canje_premio
    {
        public int id_canje { get; set; }
        public Nullable<int> id_premio { get; set; }
        public Nullable<long> id_cliente { get; set; }
        public Nullable<System.DateTime> fecha_canje { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual Premio Premio { get; set; }
    }
}
