//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PalcoNet.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item_factura
    {
        public long id_item { get; set; }
        public Nullable<long> id_ubicacion { get; set; }
        public Nullable<long> id_factura { get; set; }
        public string descripcion { get; set; }
        public decimal monto { get; set; }
        public Nullable<decimal> cantidad { get; set; }
    
        public virtual Factura Factura { get; set; }
        public virtual Ubicacion_publicacion Ubicacion_publicacion { get; set; }
    }
}
