//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PalcoNet.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Puntos_cliente
    {
        public long id_puntaje { get; set; }
        public Nullable<long> id_cliente { get; set; }
        public int puntos { get; set; }
        public System.DateTime vencimiento { get; set; }
    
        public virtual Cliente Cliente { get; set; }
    }
}
