//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PalcoNet.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Factura
    {
        public Factura()
        {
            this.Item_factura = new HashSet<Item_factura>();
        }
    
        public long id_factura { get; set; }
        public decimal numero { get; set; }
        public System.DateTime fecha { get; set; }
        public Nullable<decimal> total { get; set; }
        public string forma_pago { get; set; }
    
        public virtual ICollection<Item_factura> Item_factura { get; set; }
    }
}
