//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PalcoNet.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Grado_publicacion
    {
        public Grado_publicacion()
        {
            this.Publicacion = new HashSet<Publicacion>();
        }
    
        public int id_grado { get; set; }
        public string descripcion { get; set; }
        public decimal comision { get; set; }
        public bool habilitado { get; set; }
    
        public virtual ICollection<Publicacion> Publicacion { get; set; }
    }
}
