//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PalcoNet.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Login_fallido
    {
        public Nullable<long> id_usuario { get; set; }
        public byte nro_intento { get; set; }
    
        public virtual Usuario Usuario { get; set; }
    }
}
