//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PalcoNet.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ubicacion_publicacion
    {
        public long id_ubicacion { get; set; }
        public Nullable<long> id_publicacion { get; set; }
        public string fila { get; set; }
        public Nullable<decimal> asiento { get; set; }
        public bool sin_numerar { get; set; }
        public decimal precio { get; set; }
        public int id_tipo { get; set; }
        public Nullable<long> id_compra { get; set; }
        public Nullable<decimal> compra_cantidad { get; set; }
    
        public virtual Compra Compra { get; set; }
        public virtual Publicacion Publicacion { get; set; }
        public virtual Tipo_ubicacion Tipo_ubicacion { get; set; }
    }
}
