//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PalcoNet.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public Usuario()
        {
            this.Login_fallido = new Login_fallido();
            this.Rol = new HashSet<Rol>();
        }
    
        public long id_usuario { get; set; }
        public string usuario { get; set; }
        public string clave { get; set; }
        public bool habilitado { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual Empresa Empresa { get; set; }
        public virtual Login_fallido Login_fallido { get; set; }
        public virtual ICollection<Rol> Rol { get; set; }
    }
}
